# Generated by Django 5.2.1 on 2025-06-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='users',
            new_name='user',
        ),
    ]
